jobs:
  check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - continue-on-error: true
      name: Build android library
      run: ./gradlew :autobahn:build connectedCheck
    - continue-on-error: true
      name: Setup Crossbar
      run: 'docker run -d -p 8080:8080 --name crossbar crossbario/crossbar

        docker run -d --link crossbar -v ${PWD}/demo-gallery/python:/test crossbario/autobahn-python
        python -u /test/test_component2.py

        '
    - continue-on-error: true
      name: Run tests
      run: docker run --rm -i --link crossbar -v ${PWD}/workspace crossbario/autobahn-java:netty
        /bin/bash -c "gradle installDist -PbuildPlatform=netty && /workspace/demo-gallery/build/install/demo-gallery/bin/demo-gallery
        ws://crossbar:8080/ws"
name: main
on:
  repository_dispatch:
    types: trigger-ga___main.yml
